### ISSUE TITLE
TODO feedback

### ISSUE THREAD

**Issue by JoeMurray** [eileenmcnaughton/nz.co.fuzion.accountsync#1]
1) Accounting packages I know all allow their chart of accounts to be exported. I think there should be an extension to import a chart of accounts into civicrm_financial_account and possibly at same time (or in future version of child extension) create related records in civicrm_financial_type table. I think creating and changing the chart of accounts and then synchronizing it to CiviCRM is an infrequent use case that is better left out of scope for this extension.

3a) Overpayments and CiviAccounts. I recommend manually adjusting in CiviCRM so that the amount paid is reduced to the amount that is currently owing. 

3b) Assuming that what you mean by total amount of contribution <> sum(line items) is not a case where there is an amount still owing or a case where a refund is due, then this is a situation where a new line item needs to be added to resolve the discrepancy.

4) What is an account sync contact?

Thoughts: yes, it makes sense to me to prevent contributions and contacts who have made contributions from being deleted.

HTH.

**Comment by jorich-2000** [comment]
I am slowly manging to convert civixero over to use the quickfile (quickfile.co.uk api - i could really do with some better docs as to how you push data to teh accountsync api - specifically [accounts_data] in contact.php
$params = array(
          'accounts_display_name' => $contact['CompanyName'],
          'contact_id' => CRM_Utils_Array::value('ClientID', $contact),
          'accounts_modified_date' => $contact['UpdatedDateUTC'],
          'plugin' => 'quickfile',
          'accounts_contact_id' => $contact['ClientID'],
          'accounts_data' => json_encode($contact),
        );
        CRM_Accountsync_Hook::accountPullPreSave('contact', $contact, $save, $params);

You seem to assume the structure of data going to the api is in a xero format rather than something generic - is that right?

**Comment by eileenmcnaughton** [comment]
The intention is that civixero should be specific & that civiaccountsync should be the generic part of it.

The api that run are civixero ones ie.https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/tree/master/api/v3/Civixero
civicrm_api('civixero', 'contactpull', array());

Which calls https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/blob/master/CRM/Civixero/Contact.php#L36 - as you have highlighted.

At this point in the code 
1) it is Xero specific code - ie. in the civixero extensions not civiaccountsync
2) if is working with an array of data that has been retrieved from Xero & is translating it into the fields civicrm account sync stores. The mapping you have makes sense.

I suspect that the issue may be that CiviXero is very Civi-to-accounts centric. Ie. we have been putting contacts into Xero from CiviCRM but with contacts in the accounting system already we usually just store them to the civicrm_accounts_contact table. From there we usually match some contacts with CiviCRM contacts (usually as part of an initial set-up) but we don't normally put all the accounts contacts into CiviCRM. (The account sync table is primarily for tracking mappings)

But, for your purpose (& in civixero in the future) I would probably add another api to take the contacts out of the account_contact table & create contacts. There could be a generic version of this e.g civicrm_api('accountsync', 'contactsync', array()) which would work off display name only (& perhaps email if we tease that out into a field);

But within the extensions a more detailed version could be created because they would know how to interpret the data in the accounts_data field

**Comment by mattwire** [comment]
@eileenmcnaughton last commented in 2014 - we can probably close this!

**Comment by eileenmcnaughton** [comment]
thanks @mattwire
